#Config YML Defaults
Game:
  TeamAmount: 2
  Teams:
  - Red
  - Blue
  Spectate: true
  AmountGames: 11
  MinPlayers: 4
  Prefix: gs
  MaxPlayers: 16
  WaitTimeMin: 120
  ChooseMapBefore: false
#                            #
# Example map included below #
#                            #
Maps:
  Example:
    Name: Example
    NumTeams: 2
    WorldFileName: example
    Saving: false
    Spawns:
      '1':
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1
      '2':
        x: 1
        y: 1
        z: 1
        yaw: 1
        pitch: 1